GET http://localhost:3000/users/


POST http://localhost:3000/users/
Content-Type: application/json

{
    "name": "John Doe 3",
    "email": "jonhdoe3@email.com",
    "password": "123456"
}